# Generated by Django 5.1.2 on 2024-10-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course_name', models.CharField(default='Django Training', max_length=50)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
